---
# tasks file for vsftpd
 - name: Install package
   yum:
     name: "vsftpd"
     state: latest

 - name: start service
   service:
     name: "vsftpd"
     state: started
     enabled: yes

 - name: Put configuration from template
   template:
     src: vsftpd.j2  
     dest: /etc/vsftpd/vsftpd.conf
     backup: true
     mode: '0600'
   notify: restart_vsftpd